version: '3'

services:
  api:
    build: .
    container_name: pg-api
    command: npm run dev
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: pg-postgres
    image: postgres:10
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
