version: '3'

services:
  api:
    build: .
    container_name: pg-api
    command: npm run dev
    env_file: .env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: pg-postgres
    hostname: ${POSTGRES_HOST}
    image: postgres:10
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  test-unit:
    build: .
    command: npm run test:unit
    volumes:
      - .:/usr/app
    tty: true

  test-integration:
    build: .
    command: npm run test:integration
    volumes:
      - .:/usr/app
    env_file: .env
    depends_on:
      - postgres
    links:
      - postgres
    tty: true

  test-e2e:
    build: .
    command: npm run test:e2e
    volumes:
      - .:/usr/app
    env_file: .env
    depends_on:
      - postgres
    links:
      - postgres
    tty: true
