version: 2.1

jobs:
  checkout-code:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-`uname -s`-`uname -m` > ~/project/docker-compose
            chmod +x ~/project/docker-compose
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./
  lint:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}

      - run: |
          npm install
          npm run lint
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
  test-unit:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Create env file
          command: cp .env.example .env
      - run:
          name: Run unit tests
          command: ./docker-compose run --rm test-unit
  test-integration:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Create env file
          command: cp .env.example .env
      - run:
          name: Run integration tests
          command: ./docker-compose run --rm test-integration
  test-e2e:
    machine: true
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Create env file
          command: cp .env.example .env
      - run:
          name: Run e2e tests
          command: ./docker-compose run --rm test-e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout-code
      - lint
      - test-unit:
          requires:
            - checkout-code
      - test-integration:
          requires:
            - checkout-code
      - test-e2e:
          requires:
            - checkout-code
